# Generated by Django 2.1 on 2019-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Desigation', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date')),
                ('Job_Description', models.CharField(max_length=100)),
                ('end_date', models.DateField(verbose_name='Date')),
                ('contact', models.CharField(max_length=12)),
                ('eligibility', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
            ],
        ),
    ]
