# Generated by Django 2.1 on 2019-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0002_postjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjob',
            old_name='Job_Desigation',
            new_name='Job_Designation',
        ),
        migrations.AddField(
            model_name='postjob',
            name='image',
            field=models.ImageField(default='', upload_to='jrs/images'),
        ),
    ]
