# Generated by Django 2.1 on 2019-07-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0004_postjob_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='image',
        ),
    ]
