# Generated by Django 2.1 on 2019-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0005_remove_postjob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='course',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='grade',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='newProfilePic',
            field=models.ImageField(default='', upload_to='jrs/images'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='semester',
            field=models.CharField(default='', max_length=2),
        ),
    ]
