# Generated by Django 2.1 on 2019-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0006_auto_20190722_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='newProfilePic',
            field=models.FileField(null=True, upload_to='jrs', verbose_name=''),
        ),
    ]
