# Generated by Django 2.1 on 2019-07-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0008_uploadresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresume',
            name='Userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.StudentData'),
        ),
    ]
