# Generated by Django 2.1 on 2019-07-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0009_auto_20190724_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('Job_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.PostJob')),
                ('Resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.UploadResume')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.StudentData')),
            ],
        ),
    ]
