# Generated by Django 2.1 on 2019-07-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0011_auto_20190725_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='Resume_id',
        ),
    ]
