# Generated by Django 2.1 on 2019-08-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0012_remove_apply_resume_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(default='', max_length=100)),
                ('postedon', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postjob',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.ComData'),
        ),
        migrations.AddField(
            model_name='usernotify',
            name='Job_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.PostJob'),
        ),
        migrations.AddField(
            model_name='usernotify',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrs.StudentData'),
        ),
    ]
