# Generated by Django 2.1 on 2019-08-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0013_auto_20190801_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotify',
            name='postedon',
        ),
    ]
