# Generated by Django 2.1 on 2019-08-01 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0014_remove_usernotify_postedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotify',
            name='postedon',
            field=models.CharField(default=datetime.datetime(2019, 8, 1, 16, 58, 38, 95636), max_length=100),
        ),
    ]
