# Generated by Django 2.1 on 2019-08-01 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrs', '0015_usernotify_postedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotify',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='usernotify',
            name='postedon',
            field=models.CharField(default=datetime.datetime(2019, 8, 1, 17, 16, 40, 678062), max_length=100),
        ),
    ]
